# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d9926614b4cc94733ed8804c85471e81c638e579629a70c1cb35be4202a408f773f3c1212992cba75addb04f6e415a94cd43eeb822fc230950979a53b4d7ac1

test:
  secret_key_base: c09013f2aff618bfb7dc4f5612f4406a2b5d3c99364e54728057670d28d76ca7cbca790fc1fb32f94c03443e64ab0d75610e37c77c8df43050557468e0cbfe2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
